version: '3' # docker-composeファイルの書式バージョン。最新の’３’を指定（2019/6/27現在）
services:
  env_python:
      image: img_env_python_anaconda2002
      build: ./settings/env_python/
      container_name: 'con_env_python'
      working_dir: '/root'
      volumes:
        - ./src:/workdir
      stdin_open: true
      tty: true

  notebook:
      image: img_notebook_anaconda2002
      build: ./settings/notebook/
      container_name: 'con_notebook'
      working_dir: '/workdir'
      volumes:
        - ./src:/workdir
      ports:
        - "8888:8888"